#!/usr/bin/env python3
"""
Create HTML wrapper for current ollama_client.py
"""

import os
from pathlib import Path

def create_html_wrapper(content, filename):
    """Create an HTML wrapper for the file content"""
    html_template = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Current File: {filename}</title>
    <style>
        body {{
            font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;
            line-height: 1.6;
            margin: 40px;
            background-color: #f6f8fa;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        .header {{
            border-bottom: 2px solid #e1e4e8;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }}
        .filename {{
            font-size: 24px;
            font-weight: bold;
            color: #24292e;
            margin-bottom: 10px;
        }}
        .source {{
            color: #586069;
            font-size: 14px;
        }}
        .content {{
            background-color: #f6f8fa;
            border: 1px solid #e1e4e8;
            border-radius: 6px;
            padding: 20px;
            overflow-x: auto;
            white-space: pre-wrap;
            font-size: 13px;
            line-height: 1.45;
        }}
        .footer {{
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #e1e4e8;
            color: #586069;
            font-size: 12px;
            text-align: center;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="filename">{filename}</div>
            <div class="source">Source: Local LegalAI Project - Current Version</div>
        </div>
        <div class="content">{content}</div>
        <div class="footer">
            Generated by GitHub HTML Wrapper for Grok Access
        </div>
    </div>
</body>
</html>"""
    
    return html_template

def main():
    """Create HTML for current ollama_client.py"""
    # Read the current file
    with open('outputs/current_ollama_client.py', 'r') as f:
        content = f.read()
    
    # Create HTML wrapper
    html_content = create_html_wrapper(content, 'current_ollama_client.py')
    
    # Save HTML file
    output_dir = Path('html_outputs')
    output_dir.mkdir(exist_ok=True)
    output_path = output_dir / 'current_ollama_client.html'
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    print(f'✅ Created HTML file: {output_path}')
    print(f'📄 File size: {len(html_content)} characters')

if __name__ == "__main__":
    main() 